spring:
    application:
        name: MICROSERVICE1
        
server:
    port: 8085
    
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://13.235.59.103:8761/eureka
